apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: all-my-envs
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - env: qa
        region: us  
        type: non-prod   
        version: qa     
      - env: staging-asia
        region: asia
        type: non-prod  
        version: staging       
      - env: staging-eu
        region: eu
        type: non-prod  
        version: staging       
      - env: staging-us
        region: us
        type: non-prod  
        version: staging       
      - env: prod-eu
        region: eu  
        type: prod  
        version: prod       
      - env: prod-us
        region: us 
        type: prod
        version: prod
      - env: integration-gpu
        region: us
        type: non-prod
        version: qa
      - env: integration-non-gpu
        region: us
        type: non-prod
        version: qa       
  template:      
    metadata:
      name: '{{.env}}' 
    spec:
      # The project the application belongs to.
      project: default

      sources:
      - repoURL: https://kostis-codefresh.github.io/multi-sources-example
        chart: my-chart
        targetRevision: '0.1.0'
        helm:
          valueFiles:
          - $values/my-values/common-values.yaml
          - $values/my-values/app-version/{{.version}}-values.yaml
          - $values/my-values/env-type/{{.type}}-values.yaml
          - $values/my-values/regions/{{.region}}-values.yaml
          - $values/my-values/envs/{{.env}}-values.yaml
      - repoURL: 'https://github.com/<your_github_user>/gitops-cert-level-3-examples.git'
        targetRevision: HEAD
        ref: values
      
      # Destination cluster and namespace to deploy the application
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.env}}'

      # Sync policy
      syncPolicy:
        syncOptions:
          - CreateNamespace=true  
        automated: 
          prune: true 
          selfHeal: true 
      
